#ifndef CONFIG_H
#define CONFIG_H

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define SERVER_BASE_URL "YOUR_SERVER_URL"

#define FPGA_RX_PIN 16
#define FPGA_TX_PIN 17
#define FPGA_UART_BAUD 115200

#define LCD_COLS 16

#define TOTAL_SLOTS 4

#define WIFI_STATUS_PRINT_MS 10000
#define HTTP_TIMEOUT_MS 10000
#define SERIAL_SETUP_MS 500

#endif
